//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCv20.Tools.Web.Site.Admin.CampaignQualities {
    
    
    public partial class Create {
        
        /// <summary>
        /// qualityEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCv20.Tools.Web.Views.QualityEditor qualityEditor;
    }
}
